#!/usr/bin/env python

import sys, re

itxt = open(sys.argv[1]).read()
suffix = sys.argv[2]

m = re.match("(?P<pkgname>[@\(\)\-\w]+) \((?P<version>[\w\.-]+)(\~\w+)*\) (?P<rest>.*)", itxt)

v = re.match("(?P<version>[\d\.]+)(wg(?P<wg_ver>\d+))*", m.group('version'))
if not v.group('wg_ver'):
    newver = v.group('version') + 'wg0~' + suffix
else:
    newver = v.group('version') + ('wg%u~%s' % (int(v.group('wg_ver'))+1, suffix))

print "%s (%s) %s" % (m.group('pkgname'), newver, m.group('rest'))
print ""
print "  * autogenerated"
print ""
print " -- Troy Straszheim <straszheim@@willowgarage.com> Mon, 24 Oct 2011 13:56:11 -0700"
print ""
print ""
